//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knigi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knigi()
        {
            this.Sostav_zakaza = new HashSet<Sostav_zakaza>();
        }
    
        public long ID_knigi { get; set; }
        public string Nazvanie_knigi { get; set; }
        public string Nameavtory { get; set; }
        public string Razdel { get; set; }
        public Nullable<long> ID_razdela { get; set; }
        public Nullable<long> ID_avtory { get; set; }
        public Nullable<long> id { get; set; }
        public Nullable<long> ID_izdatelstva { get; set; }
        public string Vidizdanie { get; set; }
        public string ISBN { get; set; }
        public string Izdatelstvo { get; set; }
        public string Kolichestvo { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> Date_postavki { get; set; }
    
        public virtual Avtory Avtory { get; set; }
        public virtual Izdatelstvo Izdatelstvo1 { get; set; }
        public virtual Razdeli Razdeli { get; set; }
        public virtual Vid_izdanie Vid_izdanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sostav_zakaza> Sostav_zakaza { get; set; }
    }
}
