//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sostav_zakaza
    {
        public long Id { get; set; }
        public string Nazvanie_knigi { get; set; }
        public Nullable<long> ID_zakaza { get; set; }
        public Nullable<long> ID_knigi { get; set; }
        public string Price { get; set; }
        public string Kolichestvo { get; set; }
    
        public virtual Knigi Knigi { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
